/**:
  ros__parameters:
    common:
      on_time_buffer: 0.5
      off_time_buffer: 0.5

      pointcloud:
        range:
          dead_zone: 0.3
          buffer: 3.0
        crop_box_filter:
          x:
            max: 10.0
            min: -100.0
          z:
            max: -1.0
            min: 0.3
        voxel_grid_filter:
          x: 0.1
          y: 0.1
          z: 0.5
        clustering:
          cluster_tolerance: 0.15  #[m]
          min_cluster_height: 0.3
          min_cluster_size: 10
          max_cluster_size: 10000
        velocity_estimation:
          observation_time: 0.3
        latency: 0.3

      filter:
        min_velocity: 1.0
        moving_time: 0.5

      vehicle:
        reaction_time: 1.2
        max_velocity: 16.6 # 60km/h
        max_deceleration: -2.0

      vru:
        reaction_time: 1.2
        max_velocity: 5.5 # 20km/h
        max_deceleration: -2.0

      ego:
        reaction_time: 1.2
        min_velocity: 1.38                              # [m/s]
        max_velocity: 16.6                              # [m/s]
        max_acceleration: 1.5
        max_deceleration: -4.0
        max_positive_jerk: 5.0
        max_negative_jerk: -5.0
        nominal_deceleration: -1.5
        nominal_positive_jerk: 0.6
        nominal_negative_jerk: -0.6

      blind_spot:
        check:
          left: true
          right: false
        offset:
          inner: 0.1
          outer: 0.3

      adjacent_lane:
        offset:
          left: -0.5
          right: -0.5
