/**:
  ros__parameters:
    common:
      target_type: [pointcloud]
      # target_type: [bus, car, motorcycle, trailer, truck, pointcloud]

      on_time_buffer: 0.5
      off_time_buffer: 0.5

      pointcloud:
        range:
          static: false
          dead_zone: 0.3
          forward: 0.0
          backward: 0.0
        crop_box_filter:
          x:
            max: 10.0
            min: -100.0
          z:
            max: -1.0
            min: 0.5
        voxel_grid_filter:
          x: 0.1
          y: 0.1
          z: 0.5
        clustering:
          cluster_tolerance: 0.5  #[m]
          min_cluster_height: 0.5
          min_cluster_size: 10
          max_cluster_size: 10000
        velocity_estimation:
          observation_time: 0.3
        latency: 0.3

      filter:
        min_velocity: 1.0

      object:
        range:
          forward: 10.0
          backward: 100.0
        reaction_time: 1.2
        max_velocity: 16.6
        max_deceleration: -2.0

      vehicle:
        reaction_time: 1.2
        max_velocity: 16.6 # 60km/h
        max_deceleration: -2.0

      vru:
        reaction_time: 1.2
        max_velocity: 5.5 # 20km/h
        max_deceleration: -2.0

      ego:
        footprint_buffer: -0.5
        reaction_time: 1.2
        min_velocity: 1.38                              # [m/s]
        max_velocity: 16.6                              # [m/s]
        max_acceleration: 1.5
        max_deceleration: -4.0
        max_positive_jerk: 5.0
        max_negative_jerk: -5.0

      blind_spot:
        check:
          left: true
          right: false
        active_distance:
          start: 20.0
          end: -10.0
        offset:
          inner: 0.1
          outer: 0.3
        target_type: [vru, pointcloud]

      adjacent_lane:
        target_type: [vehicle, pointcloud]
        offset:
          left: -0.5
          right: -0.5

      predicted_path:
        time_resolution: 0.5                            # [s]
        time_horizon: 3.0
        delay_until_departure: 0.0                      # [s]
      rss:
        extended_polygon_policy: along_path             # [-] select "rectangle" or "along_path"
        vehicle_safety_time_margin: 1.0            # [s]
        lateral_distance_max_threshold: 1.8             # [m]
        longitudinal_distance_min_threshold: 3.0        # [m]
        longitudinal_velocity_delta_time: 0.0           # [s]
